# Generated by Django 4.2.26 on 2025-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(default='brian', max_length=100),
            preserve_default=False,
        ),
    ]
