# Generated by Django 4.2.26 on 2025-12-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
