# Generated by Django 4.2.26 on 2025-12-08 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0004_booking_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=800)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('specialties', models.CharField(blank=True, help_text='e.g. Strength Training, Weight Loss, Yoga, Mobility', max_length=300)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('qualifications', models.TextField(blank=True, help_text='Certifications, degrees, awards...')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Profile',
                'verbose_name_plural': 'Trainer Profiles',
            },
        ),
    ]
